### ISSUE TITLE
There are some wrong PDB IDs!!!

### ISSUE THREAD

**Issue by xiongzhp** [jonathanking/sidechainnet#21]
There are some wrong PDB IDs like '5DI3_d5di3a1', '5AHS_d5ahsf1', '3G5G_d3g5gl-' with repeating string.

**Comment by jonathanking** [comment]
These are ASTRAL IDs, not strictly PDB IDs. See https://github.com/aqlaboratory/proteinnet/issues/1#issuecomment-375270286 for more information.
