### ISSUE TITLE
There are some repeating pids in the datasets

### ISSUE THREAD

**Issue by xiongzhp** [jonathanking/sidechainnet#33]
```
data = scn.load(
    casp_version = 12,
    thinning = 30,
    with_pytorch = 'dataloaders',
    batch_size = 1,
    dynamic_batching = False,
)

for itr, batch in enumerate(data['train']):
    a_list.append(batch.pids[0])
len(a_list),len(set(a_list))
```
Which will output (25212, 15829). That is to say, only 15829 different structures in the training set?

**Comment by jonathanking** [comment]
I think I understand the confusion. SidechainNet Dataloaders randomly load the data available for batching. It will approximately load each protein once per epoch. Behind the scenes it has organized proteins by size, and picks a size bin with a probability proportional to the number of proteins in each bin. Perhaps it would be a nice feature to not load the data like this! This is just how I had loaded it for my own work. 

To get a better understanding of the number of unique IDs available, please load the data as a Python dictionary (do not provide the `with_Pytorch` argument to `scn.load`.

**Comment by jonathanking** [comment]
The actual number of IDs in this dataset is 25212 (hence why the DataLoader yields this many proteins in one epoch). ![image](https://user-images.githubusercontent.com/4186997/119264526-7195d500-bb98-11eb-91e6-22d294d80af4.jpeg)

**Comment by xiongzhp** [comment]
Yes, you are right. There are 25212 proteins.

**Comment by jonathanking** [comment]
Please let me know if I can provide any further assistance, and good luck with your work!
