### ISSUE TITLE
scn.load() error

### ISSUE THREAD

**Issue by liuxm117** [jonathanking/sidechainnet#36]
when I run python train_pre.py, it get error at scn.load(), can not get the pkl file，how can I get the pkl file before I run the program

**Comment by jonathanking** [comment]
Can you show me the code you are running?

`scn.load(12, 100)` will download the most recent and most complete dataset as a .pkl file to `./sidechainnet_data`. Hope that helps!

**Comment by liuxm117** [comment]
> Can you show me the code you are running?
> 
> `scn.load(12, 100)` will download the most recent and most complete dataset as a .pkl file to `./sidechainnet_data`. Hope that helps!

SidechainNet(12, 100) was not found in ./sidechainnet_data.
Downloading from https://pitt.box.com/shared/static/ey5xh6l4p8iwzrxtxwpxt7oeg70eayl4.pkl
^CTraceback (most recent call last):
  File "train_pre.py", line 37, in <module>
    data = scn.load(
  File "/opt/conda/lib/python3.8/site-packages/sidechainnet/utils/load.py", line 261, in load
    local_path = _download_sidechainnet(casp_version, thinning, scn_dir)
  File "/opt/conda/lib/python3.8/site-packages/sidechainnet/utils/load.py", line 76, in _download_sidechainnet
    _download(BOXURLS[format_sidechainnet_path(casp_version, thinning)], outfile_path)
  File "/opt/conda/lib/python3.8/site-packages/sidechainnet/utils/load.py", line 50, in _download
    r = requests.get(url, stream=True)
maybe My internet does not have permission，how can i download the pkl file before i run train_pre.py

**Comment by jonathanking** [comment]
Hi, is there more to the error message? Unfortunately, I can't quite see what the error is from what you have shared with me.
