### ISSUE TITLE
Custom dataset .load() broken

### ISSUE THREAD

**Issue by AllanSCosta** [jonathanking/sidechainnet#40]
Hi Jonathan,

I use the load function for loading custom datasets. With the most recent update, I think something broke in loading custom datasets:
```
  "sidechainnet/utils/load.py", line 267, in load
    scn_dict = scn.utils.manual_adjustment._repair_1GJJ_1_A(scn_dict)
  "sidechainnet/utils/manual_adjustment.py", line 72, in _repair_1GJJ_1_A
    for idx, cur_id in enumerate(datadict[split]["ids"]):
KeyError: 'valid-10'
```

Thanks
Allan

**Comment by jonathanking** [comment]
Hi Allan,

Thank you for letting me know. My apologies! I'll fix this ASAP.

Best,
Jonathan

**Comment by jonathanking** [comment]
This should work, but let me know if you are having trouble with it. Thanks again for pointing this out!

**Comment by AllanSCosta** [comment]
Worked for me, thanks :)
