### ISSUE TITLE
Are you going to release dataset for CASP-14?

### ISSUE THREAD

**Issue by jaydeepradeJD** [jonathanking/sidechainnet#47]
Hey, just wanted to ask if are you going to release the CASP-14 dataset in SideChainNet?

**Comment by jonathanking** [comment]
Thanks for your interest! At this time, SidechainNet does not support CASP 13 or 14 directly. However, there are instructions in the tutorial section of the README that explain how you can use the tools from SidechainNet with a custom list of proteins.

Please let me know if you have any more questions.

**Comment by jaydeepradeJD** [comment]
Thank you for quick reply!! I will go through it and give it a try.

**Comment by jonathanking** [comment]
You're welcome! Here is the section I was talking about: [link](https://github.com/jonathanking/sidechainnet#reproducing-or-extending-sidechainnet).

**Comment by jaydeepradeJD** [comment]
Okay Thanks!
