### ISSUE TITLE
Order of crds

### ISSUE THREAD

**Issue by ychnh** [jonathanking/sidechainnet#50]
Hi,

I was reading through the documentation and I could not find the ordering of the atom information for crds.
I did find some information that makes me guess that the ordering is [N, C_alpha, C,  O].
Could I get a confirmation for this?
Also, would you see if there are any issues if I computed Cb from N ,C_alpha, C to recompute the bond angles?

Thanks,

**Comment by jonathanking** [comment]
Hello,

Thanks for your interest and for the question. 

You are correct regarding the coordinate ordering. Please see [this file](https://github.com/jonathanking/sidechainnet/blob/master/sidechainnet/structure/build_info.py) for more information. 

Regarding Cbeta, can you please clarify what you are trying to accomplish?

Best,
Jonathan

**Comment by ychnh** [comment]
Coordinate ordering: Ah, thank you for the link.

Cbeta: I want to compute the pairwise omega, theta, pi but these require Cbeta atom positions. I could look at the cif files to obtain these or compute Cbeta from N,Calpha,C (if it is a reasonable approach).

**Comment by jonathanking** [comment]
SidechainNet includes the Cbeta atoms in its coordinate representation (see the same file I linked above). Please let me know if you need any more help.
