### ISSUE TITLE
Issue with not importing sidechainnet

### ISSUE THREAD

**Issue by Shishir8957** [jonathanking/sidechainnet#63]
![image](https://github.com/jonathanking/sidechainnet/assets/85719050/4efa3ce7-1b2c-4c8b-85b4-e9eb403f52cc)

**Comment by jonathanking** [comment]
Hi, 

OpenMM is now a required package for SidechainNet. Please see the README for a complete list of requirements. 

Best,
Jonathan

**Comment by Shishir8957** [comment]
hi jonathanking,
   I have encountered a persistent error in OpenMM despite multiple attempts. I've diligently followed the methods recommended by both ChatGPT and other sources, yet the issue persists. This is a critical problem for our final year major project, and we need assistance as we're currently unsure how to resolve it. Any help would be greatly appreciated.

![image](https://github.com/jonathanking/sidechainnet/assets/85719050/c553166c-3e49-4c12-b63e-a48fd054e2e1)
![image](https://github.com/jonathanking/sidechainnet/assets/85719050/b7b62fbc-9378-4354-96cd-fdaa67e5be40)

**Comment by jonathanking** [comment]
Ah, yeah that is unexpected! This is an issue installing OpenMM via conda. I am looking around for a solution, but haven't had luck yet. Reaching out to the OpenMM developers may be a good way forward if we cannot figure it out here.

**Comment by jonathanking** [comment]
The issue seems to be that OpenMM says it needs cudatoolkit=12.2, but this doesn't exist on the `conda-forge` or `nvidia` channels. If we downgrade the cuda toolkit version, it seems to work.

Try the following (remove `!` if not running in colab):

`!conda install -c conda-forge openmm cudatoolkit==11.8`

**Comment by Shishir8957** [comment]
use are using sidchainnet of 0.6.0 
In new version error on d['train'].key() we got error of keyword error at train 
![Uploading inbound2124685611919037866.png…]()

**Comment by jonathanking** [comment]
Please try 0.7.6 instead. Also, if you post your error here I may be able to help you solve it.

Best,
Jonathan

**Comment by Shishir8957** [comment]
use are using sidchainnet of 0.6.0 
In new version error on d['train'].key() we got error of keyword error at train 
![inbound8437265090111556072](https://github.com/jonathanking/sidechainnet/assets/85719050/1924eb5f-6467-44d1-85ec-733729950fc9)

**Comment by jonathanking** [comment]
Ah, that's correct. The new version of SidechainNet has changed the underlying format of the data. I would highly recommend using the latest version of SidechainNet. Hopefully I can assist with any further problems you find.

**Comment by Shishir8957** [comment]
1. i got this error and i solve this print("Protein IDs\n   ", batch.pids) removing print("Protein IDs\n   ", batch.ids)
![image](https://github.com/jonathanking/sidechainnet/assets/85719050/1c834af1-d848-4909-8697-957a9d4838cd)
2. 
![image](https://github.com/jonathanking/sidechainnet/assets/85719050/fa4353d6-e2c4-4d28-aae1-70e63c711622)
3. 
![image](https://github.com/jonathanking/sidechainnet/assets/85719050/1abc0a95-dc1f-4bf0-a720-6d76aa714e76)
this error is solved by 
![image](https://github.com/jonathanking/sidechainnet/assets/85719050/b5adae54-94e9-4406-99ea-85c636762778)

**Comment by Shishir8957** [comment]
Hi Jonathan King,

I hope this message finds you well. We've encountered several errors while running our Colab notebook, even after attempting a new method. Specifically, we are facing issues with the attributes of our dataset.

If it's not too much trouble, could you please take a look and run the Colab notebook? Your expertise in troubleshooting these types of issues would be immensely valuable to us. Any updates or insights you can provide will be greatly appreciated.

Thank you so much for your assistance.

https://colab.research.google.com/drive/1J5pUnPuANM6cPXaR2eVNLI6c5wfZgr3X#scrollTo=oUs2Wh5vcEaU
