### ISSUE TITLE
Missing sets / resolution

### ISSUE THREAD

**Issue by thamelry** [jonathanking/sidechainnet#64]
Hi,

For the CASP12 data set:

  * It seems the valid-60 and valid-80 data sets are missing.
  * For the test set, the proteins don't have any resolution data. The resolution attribute is always None. 

Best regards,

-Thomas

**Comment by jonathanking** [comment]
Hi Thomas,

Thanks for your interest!

Those validation set splits do not exist. Only splits of 10, 20, 30, 40, 50, 70, 90% are created. I encourage you to check out the [ProteinNet paper](https://doi.org/10.1186/s12859-019-2932-0) if you would like to learn more about the original design that we build upon in SidechainNet.

The test set proteins are downloaded from the CASP contest website, not the RCSB PDB. As such, they have special CASP-specific identifiers, and the resolution is not available from the RCSB PDB (which is where SidechainNet looks for resolution data). 

Best,
Jonathan

**Comment by jonathanking** [comment]
Closing this as I go through issues, but feel free to let me know if you have any further questions.
