### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by bondrewd** [jonathanking/sidechainnet#66]
Hi! Thank you for this amazing work!

I've been working recently with this package and found that the documentation says the thinning is passed as "thinning", but the actual argument is "casp_thinning".

https://github.com/jonathanking/sidechainnet/blob/4897c12821e742e05e97dd1426dc630b1b4a1856/sidechainnet/utils/load.py#L130

**Comment by jonathanking** [comment]
Nice catch! Thanks for letting me know. Must have missed that when I updated the code a few months ago. Should be fixed and merged momentarily! 😄
