### ISSUE TITLE
Issue installing 

### ISSUE THREAD

**Issue by Max-Witwer** [jonathanking/sidechainnet#67]
I am having trouble installing the new version this. the Colab is stopped working and normal pip installation as specified under the current conda version doesn't work. Is anyone else having trouble with this?

**Comment by dkoes** [comment]
@jonathanking are you no longer on planning on supporting this?

**Comment by jonathanking** [comment]
Hi @Max-Witwer, I'm sorry to hear you're having issues! Thanks for bringing this to my attention. Could you please clarify the issues you're having, both with the install and with the notebook? I was able to run most of the notebook, though I did run into two issues just now complaining about CUDA vs CPU and numpy vs torch. I've just corrected those. Sorry about that!

I was also just able to install the package locally. I did run into a problem using Python 3.12, but installation with Python 3.11 worked well. I'll try adding that requirement in `setup.py`. I am using the micromamba package manager, in case that happens to be a meaningful difference.

@dkoes I will do my best, but unfortunately I've had less free time than I expected at my new position. If anyone in the lab has bandwidth or is interested in support/development, I'd be happy to discuss!
