### ISSUE TITLE
Visualization error

### ISSUE THREAD

**Issue by Osos8128** [jonathanking/sidechainnet#7]
it Gives this error when i run sb.to_3Dmol()
"ValueError: Expected integer AA code.()<class 'numpy.int32'>"
i tried to change the angles array to int and error still the same 
so how this can be solved ??

**Comment by jonathanking** [comment]
Can you show more of what you're working on? It's saying that it expected the sequence component of your structure builder to be represented as integers.

**Comment by Osos8128** [comment]
data = scn.load(casp_version=12, thinning=30)
data.keys()
data['train'].keys()
Seq = data['train']['seq'][200]
Angs = data['train']['ang'][200]
Angs = Angs.astype(np.int64)
sb = scn.StructureBuilder(Seq, Angs)
sb.to_3Dmol()

im working on protein folding project using deep learning and i want to visualize the protein after testing so i try to run this code first to be sure that sb.to_3Dmol() is working i take sequence and angle from dataset to be sure that sb.to_3Dmol is working but when i run this line (sb.to_3Dmol()) it gives this error (ValueError: Expected integer AA code.()<class 'numpy.int32'>) altough the line sb = scn.StructureBuilder(Seq, Angs) run correctly and didnt return any error.

**Comment by Osos8128** [comment]
i hope this help 
![erorofside](https://user-images.githubusercontent.com/40743772/100689523-4c649e80-338d-11eb-8f63-97c04e36ca62.jpg)

**Comment by jonathanking** [comment]
Hi @Osos8128 , sorry for the late response to your issue.

I see that you're turning `Angs` into `np.int64`s. Angles are recorded as radians in the range `[-pi, pi]` and should be represented as floating-point numbers. 

Are you still having issues with the structure builder? I have recently added support so that sequences can be supplied either as strings of 1-letter amino acid codes or as integers.

**Comment by Osos8128** [comment]
Don't worry.
im commenting this line in the picture and error occured also, but i read your code and find the if condition that return this error and commenting it. and it builds pdb after that and to3Dmol() work but didn't give any output i don't know if this are spyder problem or not.

![joNIS1](https://user-images.githubusercontent.com/40743772/102287355-ef4b1a00-3f42-11eb-92f4-884b54960992.png)

**Comment by jonathanking** [comment]
I see, thanks for clarifying. I have just pushed a change to allow for `np.int32` sequences. I think that should fix the error you're getting. Please update with `git pull`. 

As to why to_3Dmol() doesn't seem to show anything, it's possible that this has something to do with Spyder. I have not tried visualizing the structures with Spyder, though I have used Google Colab and Jupyter Notebook to visualize structures successfully. Generally speaking, I would recommend those tools for debugging and playing around with this kind of code.

**Comment by jonathanking** [comment]
I'm going to mark this as closed for now, but let me know if you need any more help! 

Best,
Jonathan
