### ISSUE TITLE
PSSM + Information content

### ISSUE THREAD

**Issue by Osos8128** [jonathanking/sidechainnet#8]
how can i seperate the pssm and information content because when i print an evo for one residue it give me w numpy array with 21 number ??!!

**Comment by jonathanking** [comment]
I would recommend slicing the array/tensor to exclude the last position. Here is an example where `evo` is the data you're interested in, with a batch size of 12, where the protein length for that batch is 127. Please let me know if I can make anything more clear.

```python
>>> evo.shape
(12, 127, 21)
>>> pssm = evo[:, :, :-1]
>>> info_content = evo[:, :, -1]
```

**Comment by Osos8128** [comment]
i think it is clear now.
every residue in sequence had an array in evo of 21 value. first 20 value is the pssm and last value is the info_content
if i get it wrong please correct me and thanks in advance

**Comment by jonathanking** [comment]
That's correct! You're welcome.
